"""
Sentinel API log schemas.

This module defines the Pydantic models used for data validation (Input) 
and serialization (Output) of log records.
"""
# Import basemodel for logbase schema
# Import field for validation
# Import configdict to handle Log objects from
# databases and get them as a dictionary
from pydantic import BaseModel, Field, ConfigDict

# Import enum and datetime to put them  into the new class
from enum import Enum
from datetime import datetime, timezone
from typing import Any

# Enum for log level
class LogLevel(str, Enum):
    """
    Enumeration of allowed log severity levels.
    Inheriting from 'str' ensures the API handles text values correctly.
    """
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class LogBase(BaseModel):
    """
    Base schema for log data.

    This model defines the core attributes shared by both log ingestion (Input)
    and log retrieval (Output) models, ensuring consistency across the API.
    """

    service_name : str = Field(
        # Service name is required
        default=...,

        # Service name length
        min_length=3,
        max_length=50,

        # Description and examples for documentation
        description="The name of the service that generated this log.",
        examples=["auth-service"]
    )

    log_level: LogLevel = Field(
        # Log level is required
        default=..., 

        # Description and examples for documentation
        description="""The severity level of the log. Values must be:
                        'INFO', 'WARNING', 'ERROR', 'CRITICAL'
        """,
        examples=["INFO", "ERROR"]
    )

    message: str = Field(
        # Message is required
        default=..., 

        # Length limits
        min_length=1, 
        max_length=1000,

        # Description and examples for documentation
        description="The main descriptive text of the log event.",
        examples=["User login failed", "Database connection timeout"]
    )

    timestamp : datetime = Field(
        # If there's no timestamp provided, calculate it from timezone
        default_factory=lambda: datetime.now(timezone.utc),

        # Description and examples for documentation
        description="The UTC timestamp of the log event in ISO 8601 format",
        examples=["2026-02-27T15:30:00Z"]
    )
    
    log_metadata : dict[str, Any] = Field(
        # If there's no metadata, put it as empty
        default={},

        # Description and examples for documentation
        description="""A flexible dictionary to store additional contextual information 
        about the log event, such as user IDs, request paths, or environment details.""",
        examples=[{"user_id": 12345, "ip_address": "192.168.1.1", "version": "v1.0.2"}]
    )

class LogCreate(LogBase):
    """
    Schema for log ingestion (Input).

    This model is used to validate and parse new log entries sent to the API. 
    It inherits all core fields from LogBase for consistency.
    """
    pass

class LogResponse(LogBase):
    """
    Schema for returning log data from the database (Output).

    This model defines the structure for displaying saved logs, 
    including system-generated fields like the unique ID.
    """
    # Log id
    id: int = Field(
        description="The unique identifier generated by the database.",
        examples=[1, 105, 2304]
    )

    # User's id (User that created the log)
    user_id : int | None = Field(
        description="The id of the user that created the log.",
        examples=[1, 105, 2304]
    )

    # Organization's id
    organization_id : int | None = Field(
        description="The id of the organization that owns the log.",
        examples=[1, 105, 2304]
    )

    # New Observability & AI Fields 

    # Process time (ms)
    process_time: float | None = Field(
        default=None,
        description="The internal processing latency in seconds.",
        examples=[0.045]
    )

    # AI classification
    ai_category: str | None = Field(
        default=None,
        description="AI-generated classification of the log content.",
        examples=["Database Error", "Auth Failure"]
    )

    # AI generated risk score
    risk_score: int | None = Field(
        default=None,
        ge=0,
        le=100,
        description="AI-calculated risk level from 0 to 100.",
        examples=[1, 20, 85]
    )

    # A value to flag a a log as a anomaly (e.g. A critical log)
    is_anomaly: bool = Field(
        default=False,
        description="Flag indicating if the log was flagged as an anomaly by the AI.",
        examples=[True, False]
    )

    # Configures Pydantic to work with SQLAlchemy models
    model_config = ConfigDict(from_attributes=True)