"""
Sentinel API log schemas.

This module defines the Pydantic models used for data validation (Input) 
and serialization (Output) of logged users.
"""
# Import basemodel for logbase schema
# Import field for validation
# Import EmailStr to automatically validate format
# Import configdict to handle user objects from
# databases and get them as a dictionary
from pydantic import BaseModel, Field, EmailStr, ConfigDict

# Import enum and datetime to put them  into the new class
from enum import Enum
from datetime import datetime, timezone
from typing import Any

# Enum for User role
class UserRole(str, Enum):
    """
    Enumeration of allowed user roles.
    Inheriting from 'str' ensures the API handles text values correctly.
    """
    ADMIN = "ADMIN"
    SERVICE = "SERVICE"
    VIEWER = "VIEWER"

class UserBase(BaseModel):
    """
    Base schema for user data.

    This model defines the core attributes shared by both user register
    and logging models, ensuring consistency across the API.
    """
    username : str = Field(
        # Service name is required
        default=...,

        # Service name length
        min_length=3,
        max_length=50,

        # Description and examples for documentation
        description="The name of the registered user.",
        examples=["Mario Gonzalez", "Web-Logging"]
    )

    # Define email as EmailStr to validate email format
    email : EmailStr = Field(
        # Email is required
        default=...,

        # Email length
        min_length=3,
        max_length=255,

        # Description and examples for documentation
        description="The email of the user.",
        examples=["daniel@gmail.com", "enterprise@outlook.com"]
    )

class UserCreate(UserBase):
    """
    Schema for user's register

    This model is used to validate and parse new users.
    It inherits all core fields from UserBase for consistency.
    """
    password : str = Field(
        # Password is required
        default=...,

        # Password length
        min_length=8,

        # Description and examples for documentation
        description="The password of the user.",
        examples=["ILOVEMYSELF2020", "theOdd1sout"]
    )

    # Organization's id
    organization_id : int = Field(
        # Organization is required
        default=...,

        # Description and examples for documentation
        description="The id of the organization that user belongs to.",
        examples=[1, 105, 2304]
    )

class UserResponse(UserBase):
    """
    Schema for returning user from de database.

    This model defines structure to allow users login,
    including system-generated fields like role and is_active.
    """

    # Unique ID
    id: int = Field(
        # Description and examples for documentation
        description="The unique identifier generated by the database.",
        examples=[1, 105, 2304]
    )

    # Validate user is active
    is_active: bool = Field(
        # Description and examples for documentation
        description="Value to validate if user is active.",
        examples=[True, False]
    )

    # Return role from Database
    role: UserRole = Field(
        # Description and examples for documentation
        description="""User role generated by the database.
                        Must be: 'ADMIN', 'SERVICE', 'VIEWER'.
        """,
        examples=["ADMIN", "SERVICE"]
    )
    
    # Organization's id
    organization_id : int = Field(
        # Description and examples for documentation
        description="The id of the organization that user belongs to.",
        examples=[1, 105, 2304]
    )

    # Return timestamps from database
    created_at: datetime = Field(
        # Description and examples for documentation
        description="The exact UTC moment the user was created.",
        examples=["2024-03-20T10:00:00Z"]
    )
    
    updated_at: datetime = Field(
        # Description and examples for documentation
        description="The last time any field in this user record was changed.",
        examples=["2024-03-21T15:30:00Z"]
    )

    # Configures Pydantic to work with SQLAlchemy models
    model_config = ConfigDict(from_attributes=True)

class UserLogin(BaseModel):
    """
    Schema for user login.

    This model defines required data to validate user login data.
    """
    email: EmailStr
    password: str

    model_config = ConfigDict(from_attributes=True)