"""add ai and observability columns to logs

Revision ID: 3c2fe85d3480
Revises: 24eb44eada1a
Create Date: 2026-03-24 17:05:40.371721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2fe85d3480'
down_revision: Union[str, Sequence[str], None] = '24eb44eada1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('process_time', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('ai_category', sa.String(length=50), nullable=True))
    op.add_column('logs', sa.Column('risk_score', sa.SmallInteger(), nullable=True))
    op.add_column('logs', sa.Column('is_anomaly', sa.Boolean(), server_default='false', nullable=True))
    op.create_index(op.f('ix_logs_ai_category'), 'logs', ['ai_category'], unique=False)
    op.create_index(op.f('ix_logs_is_anomaly'), 'logs', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_logs_risk_score'), 'logs', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_risk_score'), table_name='logs')
    op.drop_index(op.f('ix_logs_is_anomaly'), table_name='logs')
    op.drop_index(op.f('ix_logs_ai_category'), table_name='logs')
    op.drop_column('logs', 'is_anomaly')
    op.drop_column('logs', 'risk_score')
    op.drop_column('logs', 'ai_category')
    op.drop_column('logs', 'process_time')
    # ### end Alembic commands ###
