"""create_ai_and_alerts_v0.7.0

Revision ID: b83bc3094d03
Revises: 3c2fe85d3480
Create Date: 2026-03-27 12:44:22.128657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b83bc3094d03'
down_revision: Union[str, Sequence[str], None] = '3c2fe85d3480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('inference_time_ms', sa.Float(), nullable=False),
    sa.Column('analysis_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_log_id'), 'ai_analyses', ['log_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.drop_index(op.f('ix_logs_ai_category'), table_name='logs')
    op.drop_index(op.f('ix_logs_is_anomaly'), table_name='logs')
    op.drop_index(op.f('ix_logs_risk_score'), table_name='logs')
    op.drop_column('logs', 'ai_category')
    op.drop_column('logs', 'risk_score')
    op.drop_column('logs', 'is_anomaly')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('is_anomaly', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('risk_score', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('ai_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_logs_risk_score'), 'logs', ['risk_score'], unique=False)
    op.create_index(op.f('ix_logs_is_anomaly'), 'logs', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_logs_ai_category'), 'logs', ['ai_category'], unique=False)
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_analyses_log_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
